[profile.default]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
"@openzeppelin/=lib/openzeppelin-contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]